/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System */
        get: operations["system_api_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/run-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Config
         * @description `run_config` is the RunConfig schema; `backbone_options` maps backbone to Options schema.
         */
        get: operations["run_config_api_schema_run_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets */
        get: operations["datasets_api_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset */
        get: operations["dataset_api_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["ingest_api_datasets__dataset_id__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Series
         * @description Bucket means over [start, end]; times are dataset-local and offsets are ignored.
         */
        get: operations["series_api_datasets__dataset_id__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Channels */
        put: operations["put_channels_api_datasets__dataset_id__channels_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backbones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backbones */
        get: operations["backbones_api_backbones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_runs_get"];
        put?: never;
        /** Submit */
        post: operations["submit_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run */
        get: operations["run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description SSE of events.jsonl. Event ids are line numbers; the stream starts after the given id.
         */
        get: operations["events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description metrics.json of the run; see the parent design section 6.1.
         */
        get: operations["metrics_api_runs__run_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Predictions
         * @description Without origin_time: the thinned origin list. With origin_time: the rows of that origin.
         */
        get: operations["predictions_api_runs__run_id__predictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare
         * @description `run_ids` is a comma-separated list of run ids.
         */
        get: operations["compare_api_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Templates */
        get: operations["templates_api_run_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run-templates/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Template */
        get: operations["get_template_api_run_templates__name__get"];
        /** Put Template */
        put: operations["put_template_api_run_templates__name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BackboneConfig */
        BackboneConfig: {
            /**
             * Name
             * @description Backbone registry name.
             */
            name: string;
            /**
             * Checkpoint
             * @description Hugging Face repository or local checkpoint directory.
             */
            checkpoint?: string | null;
            /**
             * Revision
             * @description Checkpoint revision to resolve.
             */
            revision?: string | null;
            /**
             * Device
             * @description Execution device.
             * @default cuda
             * @enum {string}
             */
            device: "cuda" | "cpu";
            /**
             * Dtype
             * @description CUDA numeric type.
             * @default bf16
             * @enum {string}
             */
            dtype: "fp32" | "bf16";
            /**
             * Options
             * @description Adapter-specific options.
             */
            options?: {
                [key: string]: unknown;
            };
        };
        /** BackboneInfo */
        BackboneInfo: {
            /** Name */
            name: string;
            capabilities: components["schemas"]["Capabilities"];
            /** Options Schema */
            options_schema: {
                [key: string]: unknown;
            };
            /** Requires */
            requires: string[];
            /** Installed */
            installed: boolean;
            /** Default Checkpoint */
            default_checkpoint: string | null;
            /** License */
            license: string | null;
            /** License Url */
            license_url: string | null;
        };
        /** Capabilities */
        Capabilities: {
            /** Forecast Modes */
            forecast_modes: ("zero_shot" | "lora" | "head" | "full")[];
            /** Embed */
            embed: boolean;
            /** Quantiles */
            quantiles: boolean;
            /**
             * Multivariate
             * @enum {string}
             */
            multivariate: "native" | "channel_independent" | "none";
            /** Max Context */
            max_context?: number | null;
            /** Max Horizon */
            max_horizon?: number | null;
            /**
             * Needs Fit Stats
             * @default false
             */
            needs_fit_stats: boolean;
        };
        /** ChannelSpec */
        ChannelSpec: {
            /**
             * Name
             * @description Exact source column name.
             */
            name: string;
            /**
             * Role
             * @description Channel role.
             * @default target
             * @enum {string}
             */
            role: "target" | "past_covariate" | "known_future_covariate" | "ignore";
            /**
             * Unit
             * @description Physical unit.
             */
            unit?: string | null;
            /**
             * Description
             * @description Channel documentation.
             */
            description?: string | null;
        };
        /** ChannelsIn */
        ChannelsIn: {
            /**
             * Channels
             * @description All channels; only role, unit, and description can change.
             */
            channels: components["schemas"]["ChannelSpec"][];
        };
        /** ChannelsOut */
        ChannelsOut: {
            /** Config Hash */
            config_hash: string;
            /** Needs Ingest */
            needs_ingest: boolean;
            config: components["schemas"]["DatasetConfig"];
        };
        /** ClassifyTaskConfig */
        ClassifyTaskConfig: {
            /**
             * @description Task type. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "classify";
            /**
             * Context Length
             * @description Context length in grid steps.
             */
            context_length: number;
            /**
             * Eval Splits
             * @description Evaluated splits.
             */
            eval_splits?: ("val" | "cal" | "test")[];
            /**
             * Train Origin Stride
             * @description Training origin stride.
             * @default 1
             */
            train_origin_stride: number;
            /**
             * Eval Origin Stride
             * @description Evaluation origin stride.
             * @default 1
             */
            eval_origin_stride: number;
            /**
             * Max Train Origins
             * @description Evenly spaced training origin limit.
             * @default 20000
             */
            max_train_origins: number;
            /**
             * Max Eval Origins
             * @description Evenly spaced evaluation origin limit; null is no limit.
             */
            max_eval_origins?: number | null;
            /** @description Future event label rule. */
            label: components["schemas"]["FutureEventRule"];
            /** @description Classifier head. */
            head?: components["schemas"]["HeadConfig"];
            /**
             * Embed Batch Size
             * @description Representation batch size.
             * @default 64
             */
            embed_batch_size: number;
        };
        /** CompareColumnOut */
        CompareColumnOut: {
            /** Run Id */
            run_id: string;
            /** Name */
            name: string;
            /** Dataset */
            dataset: string;
            /** Task */
            task: string | null;
            /** Backbone */
            backbone: string | null;
            /** Mode */
            mode: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted";
            /** Context Length */
            context_length: number | null;
            /** Horizon */
            horizon: number | null;
        };
        /** CompareOut */
        CompareOut: {
            /** Columns */
            columns: components["schemas"]["CompareColumnOut"][];
            /** Rows */
            rows: components["schemas"]["CompareRowOut"][];
            /** Warnings */
            warnings: components["schemas"]["CompareWarningOut"][];
        };
        /** CompareRowOut */
        CompareRowOut: {
            /** Split */
            split: string;
            /** Metric */
            metric: string;
            /**
             * Values
             * @description Value per run id.
             */
            values: {
                [key: string]: number | null;
            };
        };
        /** CompareWarningOut */
        CompareWarningOut: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** Condition */
        Condition: {
            /**
             * Channel
             * @description Channel to compare.
             */
            channel: string;
            /**
             * Op
             * @description Comparison.
             * @enum {string}
             */
            op: "gt" | "ge" | "lt" | "le" | "eq" | "ne";
            /**
             * Value
             * @description Comparison threshold.
             */
            value: number;
        };
        /** ConditionGroup */
        ConditionGroup: {
            /**
             * All
             * @description All child rules must match.
             */
            all?: (components["schemas"]["Condition"] | components["schemas"]["ConditionGroup"])[] | null;
            /**
             * Any
             * @description At least one child rule must match.
             */
            any?: (components["schemas"]["Condition"] | components["schemas"]["ConditionGroup"])[] | null;
        };
        /** DatasetConfig */
        DatasetConfig: {
            /**
             * Id
             * @description Dataset file stem.
             */
            id: string;
            /** @description Source file configuration. */
            source: components["schemas"]["SourceConfig"];
            /**
             * Native Freq
             * @description Native sampling interval.
             */
            native_freq: string;
            /**
             * Freq
             * @description Prepared grid interval.
             */
            freq: string;
            /**
             * Aggregation
             * @description Bin aggregation.
             * @default mean
             * @enum {string}
             */
            aggregation: "mean" | "last";
            /**
             * Dedup
             * @description Duplicate policy.
             * @default keep_last
             * @enum {string}
             */
            dedup: "keep_first" | "keep_last";
            /**
             * Channels
             * @description Channels, or automatic numeric discovery.
             */
            channels?: components["schemas"]["ChannelSpec"][] | null;
            /** @description Eligibility rules, or any non-null channel. */
            eligibility?: components["schemas"]["ConditionGroup"] | null;
            /** @description Continuous segment rules. */
            segments: components["schemas"]["SegmentConfig"];
            /** @description Chronological split rules. */
            split?: components["schemas"]["SplitConfig"];
        };
        /** DatasetDetailOut */
        DatasetDetailOut: {
            /** Id */
            id: string;
            /**
             * Status
             * @description Cache state of the current configuration.
             * @enum {string}
             */
            status: "fresh" | "stale" | "missing";
            /** Config Hash */
            config_hash: string;
            config: components["schemas"]["DatasetConfig"];
            /**
             * Meta
             * @description Cache metadata; null unless fresh.
             */
            meta: {
                [key: string]: unknown;
            } | null;
        };
        /** DatasetOut */
        DatasetOut: {
            /** Id */
            id: string;
            /**
             * Status
             * @description Cache state of the current configuration.
             * @enum {string}
             */
            status: "fresh" | "stale" | "missing";
            /** Config Hash */
            config_hash: string;
            config: components["schemas"]["DatasetConfig"];
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Detail */
            detail?: unknown;
        };
        /** ErrorOut */
        ErrorOut: {
            error: components["schemas"]["ErrorBody"];
        };
        /** FinetuneConfig */
        FinetuneConfig: {
            /**
             * Learning Rate
             * @description Optimizer learning rate.
             * @default 0.00001
             */
            learning_rate: number;
            /**
             * Num Steps
             * @description Number of optimizer steps.
             * @default 1000
             */
            num_steps: number;
            /**
             * Batch Size
             * @description Training batch size.
             * @default 64
             */
            batch_size: number;
            /**
             * Eval Every
             * @description Validation interval in steps.
             * @default 100
             */
            eval_every: number;
            /**
             * Grad Clip
             * @description Maximum gradient norm.
             * @default 1
             */
            grad_clip: number;
            /** @description Low-rank adapter settings. */
            lora?: components["schemas"]["LoraSpec"];
        };
        /** ForecastTaskConfig */
        ForecastTaskConfig: {
            /**
             * @description Task type. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "forecast";
            /**
             * Context Length
             * @description Context length in grid steps.
             */
            context_length: number;
            /**
             * Horizon
             * @description Forecast horizon in grid steps.
             */
            horizon: number;
            /**
             * Eval Leads
             * @description Lead steps (1-based) that get separate metrics.
             */
            eval_leads?: number[];
            /**
             * Eval Splits
             * @description Evaluated splits.
             */
            eval_splits?: ("val" | "cal" | "test")[];
            /**
             * Train Origin Stride
             * @description Training origin stride. Adapters sample forecast training windows from fit segments, so forecast runs do not use this value.
             * @default 1
             */
            train_origin_stride: number;
            /**
             * Eval Origin Stride
             * @description Evaluation origin stride.
             * @default 1
             */
            eval_origin_stride: number;
            /**
             * Max Eval Origins
             * @description Evenly spaced evaluation origin limit; null is no limit.
             */
            max_eval_origins?: number | null;
            /**
             * Eval Batch Size
             * @description Forecast batch size.
             * @default 64
             */
            eval_batch_size: number;
        };
        /** FutureEventRule */
        FutureEventRule: {
            /**
             * Type
             * @description Label rule type.
             * @default future_event
             * @constant
             */
            type: "future_event";
            /**
             * Channel
             * @description Event channel.
             */
            channel: string;
            /**
             * Op
             * @description Event comparison.
             * @enum {string}
             */
            op: "gt" | "lt" | "outside";
            /**
             * Threshold
             * @description Threshold definition.
             */
            threshold: components["schemas"]["ThresholdSpec"] | components["schemas"]["OutsideThreshold"];
            /**
             * Window
             * @description Future window length in grid steps.
             */
            window: number;
            /**
             * Min Duration
             * @description Consecutive event steps required.
             */
            min_duration: number;
        };
        /** GpuOut */
        GpuOut: {
            /** Index */
            index: number;
            /** Name */
            name: string;
            /** Memory Total Mb */
            memory_total_mb: number;
            /** Memory Used Mb */
            memory_used_mb: number;
            /** Driver Version */
            driver_version: string;
        };
        /** HeadConfig */
        HeadConfig: {
            /**
             * Type
             * @description Classifier head.
             * @default logistic
             * @enum {string}
             */
            type: "logistic" | "mlp";
            /**
             * Class Weight
             * @description Class weighting; null gives equal sample weights.
             * @default balanced
             */
            class_weight: "balanced" | null;
            /**
             * C
             * @description Inverse regularization for logistic heads.
             * @default 1
             */
            C: number;
            /**
             * Hidden Layer Sizes
             * @description Hidden layer sizes for MLP heads.
             */
            hidden_layer_sizes?: number[];
            /**
             * Max Iter
             * @description Maximum solver iterations.
             * @default 1000
             */
            max_iter: number;
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** JobSpec */
        JobSpec: {
            /**
             * Kind
             * @description Job kind.
             * @enum {string}
             */
            kind: "experiment" | "ingest";
            /** @description Dataset configuration snapshot. */
            dataset: components["schemas"]["DatasetConfig"];
            /** @description Run configuration; null for ingest. */
            run?: components["schemas"]["RunConfig"] | null;
        };
        /** LoraSpec */
        LoraSpec: {
            /**
             * R
             * @description Low-rank adapter rank.
             * @default 8
             */
            r: number;
            /**
             * Alpha
             * @description Low-rank adapter scaling factor.
             * @default 16
             */
            alpha: number;
            /**
             * Dropout
             * @description Adapter dropout rate.
             * @default 0.05
             */
            dropout: number;
            /**
             * Target Modules
             * @description Module names; null selects the adapter defaults.
             */
            target_modules?: string[] | null;
        };
        /** OutsideThreshold */
        OutsideThreshold: {
            /**
             * Low
             * @description Lower fixed threshold or fit quantile.
             */
            low: components["schemas"]["ThresholdSpec"] | number;
            /**
             * High
             * @description Upper fixed threshold or fit quantile.
             */
            high: components["schemas"]["ThresholdSpec"] | number;
        };
        /** PredictionsOut */
        PredictionsOut: {
            /** Split */
            split: string;
            /**
             * Origin Time
             * @description Requested origin; null for the origin list.
             */
            origin_time: string | null;
            /**
             * Origins
             * @description Thinned origin list without origin_time.
             */
            origins: string[] | null;
            /**
             * Total Origins
             * @description Origin count before thinning.
             */
            total_origins: number | null;
            /**
             * Rows
             * @description Prediction rows of origin_time.
             */
            rows: {
                [key: string]: unknown;
            }[] | null;
        };
        /** RunConfig */
        RunConfig: {
            /**
             * Name
             * @description Run name.
             */
            name: string;
            /**
             * Dataset
             * @description Dataset id.
             */
            dataset: string;
            /**
             * Task
             * @description Task configuration.
             */
            task: components["schemas"]["ForecastTaskConfig"] | components["schemas"]["ClassifyTaskConfig"];
            /** @description Backbone configuration. */
            backbone: components["schemas"]["BackboneConfig"];
            /**
             * Mode
             * @description Training mode; classification requires head.
             * @enum {string}
             */
            mode: "zero_shot" | "lora" | "head" | "full";
            /** @description Fine-tuning settings; zero_shot ignores them. */
            finetune?: components["schemas"]["FinetuneConfig"];
            /**
             * Seed
             * @description Random seed.
             * @default 0
             */
            seed: number;
            /**
             * Notes
             * @description Free-text notes.
             * @default
             */
            notes: string;
        };
        /** RunDetailOut */
        RunDetailOut: {
            /** Run Id */
            run_id: string;
            job: components["schemas"]["JobSpec"];
            status: components["schemas"]["RunStatus"];
            /** Env */
            env: {
                [key: string]: unknown;
            } | null;
        };
        /** RunStatus */
        RunStatus: {
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Pid */
            pid?: number | null;
            /** Error */
            error?: string | null;
        };
        /** RunSubmittedOut */
        RunSubmittedOut: {
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunStatus"];
        };
        /** RunSummary */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "experiment" | "ingest";
            /** Dataset */
            dataset: string;
            /** Task */
            task: string | null;
            /** Backbone */
            backbone: string | null;
            /** Mode */
            mode: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Primary Metric */
            primary_metric: string | null;
            /** Primary Value */
            primary_value: number | null;
        };
        /** SegmentConfig */
        SegmentConfig: {
            /**
             * Max Gap
             * @description Maximum internal interruption duration.
             */
            max_gap: string;
            /**
             * Min Length
             * @description Minimum segment duration, including grid steps.
             */
            min_length: string;
        };
        /** SegmentOut */
        SegmentOut: {
            /** Segment Id */
            segment_id: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Length */
            length: number;
            /** Duration Seconds */
            duration_seconds: number;
            /** Eligible Points */
            eligible_points: number;
        };
        /** SeriesOut */
        SeriesOut: {
            /**
             * Every
             * @description Bucket width; buckets are labelled with their start time.
             */
            every: string;
            /** Time */
            time: string[];
            /** Values */
            values: {
                [key: string]: (number | null)[];
            };
            /** Segments */
            segments: components["schemas"]["SegmentOut"][];
            /** Split Boundaries */
            split_boundaries: {
                [key: string]: string;
            };
        };
        /** SourceConfig */
        SourceConfig: {
            /**
             * Path
             * Format: path
             * @description Source file path.
             */
            path: string;
            /**
             * Format
             * @description Source format.
             * @default csv
             * @enum {string}
             */
            format: "csv" | "parquet";
            /**
             * Encoding
             * @description CSV encoding.
             * @default utf8
             * @enum {string}
             */
            encoding: "utf8" | "utf8-lossy";
            /**
             * Time Column
             * @description Timestamp column name.
             */
            time_column: string;
            /**
             * Time Format
             * @description Timestamp format, or ISO discovery.
             */
            time_format?: string | null;
        };
        /** SplitConfig */
        SplitConfig: {
            /**
             * Ratios
             * @description Fit, val, cal, test proportions.
             * @default [
             *       0.7,
             *       0.1,
             *       0.1,
             *       0.1
             *     ]
             */
            ratios: [
                number,
                number,
                number,
                number
            ];
            /**
             * Basis
             * @description Boundary count basis.
             * @default eligible_points
             * @constant
             */
            basis: "eligible_points";
        };
        /** SystemOut */
        SystemOut: {
            /** Python */
            python: string;
            /** Platform */
            platform: string;
            /** Packages */
            packages: {
                [key: string]: string | null;
            };
            /** Gpus */
            gpus: components["schemas"]["GpuOut"][];
            /** Runs Dir */
            runs_dir: string;
            /** Cache Dir */
            cache_dir: string;
            /** Configs Dir */
            configs_dir: string;
            /** Gpu Slots */
            gpu_slots: number;
            /** Cpu Slots */
            cpu_slots: number;
        };
        /** TemplateOut */
        TemplateOut: {
            /** Name */
            name: string;
        };
        /** ThresholdSpec */
        ThresholdSpec: {
            /**
             * Quantile
             * @description Eligible fit quantile.
             */
            quantile?: number | null;
            /**
             * Value
             * @description Fixed threshold.
             */
            value?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    system_api_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    run_config_api_schema_run_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    datasets_api_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    dataset_api_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetDetailOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    ingest_api_datasets__dataset_id__ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSubmittedOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    series_api_datasets__dataset_id__series_get: {
        parameters: {
            query?: {
                /** @description Repeat for each channel. */
                channels?: string[] | null;
                start?: string | null;
                end?: string | null;
                max_points?: number;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    put_channels_api_datasets__dataset_id__channels_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelsOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    backbones_api_backbones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackboneInfo"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    submit_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSubmittedOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    cancel_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    events_api_runs__run_id__events_get: {
        parameters: {
            query?: {
                from?: number | null;
            };
            header?: {
                "last-event-id"?: number | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    metrics_api_runs__run_id__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    predictions_api_runs__run_id__predictions_get: {
        parameters: {
            query: {
                split: "val" | "cal" | "test";
                channel?: string | null;
                origin_time?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionsOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    compare_api_compare_get: {
        parameters: {
            query: {
                run_ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    templates_api_run_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_template_api_run_templates__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunConfig"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    put_template_api_run_templates__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunConfig"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
